Repository Southeastern-Louisiana-University/cmps383-2023-sp-p03-g02, pull requests merged in 2023-03, with the labels that each got.

#7 Adding typescript
  SP23.P03.Web/ClientApp/package-lock.json
  SP23.P03.Web/ClientApp/package.json
  SP23.P03.Web/ClientApp/src/App.test.tsx
  SP23.P03.Web/ClientApp/src/App.tsx
  SP23.P03.Web/ClientApp/src/custom.d.ts
  SP23.P03.Web/ClientApp/src/index.tsx
  SP23.P03.Web/ClientApp/tsconfig.json
Labels: enhancement

#8 Fix connection string
  SP23.P03.Web/appsettings.json
Labels: bug

#11 Frontend and UI stuff
  SP23.P03.Web/ClientApp/package-lock.json
  SP23.P03.Web/ClientApp/package.json
  SP23.P03.Web/ClientApp/src/components/ExtraIcon.tsx
  SP23.P03.Web/ClientApp/src/index.tsx
Labels: enhancement

#16 Frontend setup
  SP23.P03.Web/ClientApp/package-lock.json
  SP23.P03.Web/ClientApp/package.json
  SP23.P03.Web/ClientApp/public/entrack-logo.svg
  SP23.P03.Web/ClientApp/public/index.html
  SP23.P03.Web/ClientApp/public/manifest.json
  SP23.P03.Web/ClientApp/src/App.test.tsx
  SP23.P03.Web/ClientApp/src/App.tsx
  SP23.P03.Web/ClientApp/src/assets/entrack-logo.svg
  SP23.P03.Web/ClientApp/src/constants/custom.d.ts
  SP23.P03.Web/ClientApp/src/constants/routeconfig.tsx
  SP23.P03.Web/ClientApp/src/index.css
  SP23.P03.Web/ClientApp/src/index.tsx
  SP23.P03.Web/ClientApp/src/logo.svg
  SP23.P03.Web/ClientApp/src/pages/Home/HomePage.tsx
  SP23.P03.Web/ClientApp/src/pages/NotFound/NotFoundPage.tsx
  SP23.P03.Web/ClientApp/src/reportWebVitals.js
  SP23.P03.Web/ClientApp/src/setupTests.js
Labels: enhancement

#18 Navbar style
  SP23.P03.Web/ClientApp/src/App.css
  SP23.P03.Web/ClientApp/src/App.tsx
  SP23.P03.Web/ClientApp/src/assets/EnTrack_HomeLogo.png
  SP23.P03.Web/ClientApp/src/components/Nav/Navbar.tsx
  SP23.P03.Web/ClientApp/src/components/Nav/NavbarStyling.css
Labels: enhancement

#19 Homepage style
  SP23.P03.Web/ClientApp/src/assets/home-background-compressed.jpg
  SP23.P03.Web/ClientApp/src/assets/home-background.jpg
  SP23.P03.Web/ClientApp/src/pages/Home/HomePage.css
  SP23.P03.Web/ClientApp/src/pages/Home/HomePage.tsx
Labels: enhancement

#21 Authentication
  SP23.P03.Web/ClientApp/package-lock.json
  SP23.P03.Web/ClientApp/package.json
  SP23.P03.Web/ClientApp/src/App.tsx
  SP23.P03.Web/ClientApp/src/components/AuthProvider.tsx
  SP23.P03.Web/ClientApp/src/components/LoginModal.tsx
  SP23.P03.Web/ClientApp/src/components/Nav/Navbar.tsx
  SP23.P03.Web/ClientApp/src/hooks/useSubscription.tsx
  SP23.P03.Web/ClientApp/src/index.tsx
  SP23.P03.Web/ClientApp/src/pages/Home/HomePage.tsx
  SP23.P03.Web/ClientApp/src/types/authentication.tsx
Labels: enhancement

#20 Navbar color scheme/style improvements
  SP23.P03.Web/ClientApp/src/App.css
  SP23.P03.Web/ClientApp/src/components/Nav/Navbar.tsx
  SP23.P03.Web/ClientApp/src/components/Nav/NavbarStyling.css
Labels: enhancement

#24 Add login modal loading indicator
  SP23.P03.Web/ClientApp/src/components/LoginModal.tsx
Labels: enhancement

#30 Feat/mobile
  SP23-P03-Mobile/App.js
  SP23-P03-Mobile/App.tsx
  SP23-P03-Mobile/assets/EnTrack_HomeLogo.png
  SP23-P03-Mobile/package-lock.json
  SP23-P03-Mobile/package.json
  SP23-P03-Mobile/src/components/AnimatedBar.tsx
  SP23-P03-Mobile/src/components/AuthProvider.tsx
  SP23-P03-Mobile/src/components/BoardingPassList.tsx
  SP23-P03-Mobile/src/components/Login.tsx
  SP23-P03-Mobile/src/components/MainLogo.tsx
  SP23-P03-Mobile/src/components/ScreenRouter.tsx
  SP23-P03-Mobile/src/constants/api.tsx
  SP23-P03-Mobile/src/constants/custom.d.ts
  SP23-P03-Mobile/src/hooks/useSubscription.tsx
  SP23-P03-Mobile/src/screens/LoginScreen.tsx
  SP23-P03-Mobile/src/screens/LogoutScreen.tsx
  SP23-P03-Mobile/src/style/colors.tsx
  SP23-P03-Mobile/src/types/authentication.tsx
  SP23-P03-Mobile/src/types/boardingpasses.tsx
  SP23-P03-Mobile/src/types/passengers.tsx
  SP23-P03-Mobile/src/types/trains.tsx
  SP23-P03-Mobile/src/types/trainstations.tsx
  SP23-P03-Mobile/src/types/trips.tsx
  SP23-P03-Mobile/tsconfig.json
Labels: feature, frontend

#32 Componentize RoutePlanner
  SP23.P03.Web/ClientApp/src/components/RoutePlanner/RoutePlanner.css
  SP23.P03.Web/ClientApp/src/components/RoutePlanner/RoutePlanner.tsx
  SP23.P03.Web/ClientApp/src/pages/Home/HomePage.css
  SP23.P03.Web/ClientApp/src/pages/Home/HomePage.tsx
  SP23.P03.Web/ClientApp/src/pages/RoutePlanning/RoutePlanning.css
  SP23.P03.Web/ClientApp/src/pages/RoutePlanning/RoutePlanning.tsx
Labels: feature, frontend
