Repository Southeastern-Louisiana-University/cmps383-2023-sp-p03-g02, pull requests merged in 2023-04, with the labels that each got.

#33 Remove Light Theme
  SP23.P03.Web/ClientApp/src/App.css
Labels: bug, frontend

#36 Fix logo SVG
  SP23.P03.Web/ClientApp/public/entrack-logo.svg
  SP23.P03.Web/ClientApp/src/assets/entrack-logo.svg
Labels: fix, frontend

#35 Mobile Boarding Pass List improvements + general mobile improvements
  SP23-P03-Mobile/App.tsx
  SP23-P03-Mobile/app.json
  SP23-P03-Mobile/assets/EnTrack_Logo_white.png
  SP23-P03-Mobile/assets/Entrack_Logo_maincolor.png
  SP23-P03-Mobile/assets/icon.png
  SP23-P03-Mobile/assets/splash.png
  SP23-P03-Mobile/package-lock.json
  SP23-P03-Mobile/package.json
  SP23-P03-Mobile/src/components/AuthProvider.tsx
  SP23-P03-Mobile/src/components/BoardingPassList.tsx
  SP23-P03-Mobile/src/components/MainLogo.tsx
  SP23-P03-Mobile/src/components/ScreenRouter.tsx
  SP23-P03-Mobile/src/components/ScreenWrapper.tsx
  SP23-P03-Mobile/src/helpers/formatters.tsx
  SP23-P03-Mobile/src/screens/BoardingPassesScreen.tsx
  SP23-P03-Mobile/src/screens/IndexScreen.tsx
  SP23-P03-Mobile/src/screens/LoginScreen.tsx
  SP23-P03-Mobile/src/screens/LogoutScreen.tsx
  SP23-P03-Mobile/src/style/styles.tsx
Labels: feature, frontend

#47 Feat/route component
  SP23.P03.Web/ClientApp/package-lock.json
  SP23.P03.Web/ClientApp/package.json
  SP23.P03.Web/ClientApp/src/components/RoutePlanner/RoutePlanner.css
  SP23.P03.Web/ClientApp/src/components/RoutePlanner/RoutePlanner.tsx
  SP23.P03.Web/ClientApp/src/components/StationSelection.tsx
  SP23.P03.Web/ClientApp/src/helpers/time.tsx
  SP23.P03.Web/ClientApp/src/pages/Home/HomePage.css
Labels: feature, frontend

#41 Mobile touchups
  SP23-P03-Mobile/app.json
  SP23-P03-Mobile/package-lock.json
  SP23-P03-Mobile/package.json
  SP23-P03-Mobile/src/components/BoardingPassList.tsx
  SP23-P03-Mobile/src/components/Login.tsx
Labels: feature, frontend

#49 Change "Capacity" to "Seats Left" on route planning page (client request)
  SP23.P03.Web/ClientApp/src/pages/RoutePlanning/RouteListing.tsx
Labels: feature, frontend

#51 Feat/real stations
  SP23.P03.Web/Data/SeedHelper.cs
Labels: feature, backend

#55 Adds print button to boarding pass modal
  SP23.P03.Web/ClientApp/src/pages/BoardingPasses/BoardingPassesPage.css
  SP23.P03.Web/ClientApp/src/pages/BoardingPasses/BoardingPassesPage.tsx
Labels: feature, frontend

#62 Signup page
  SP23.P03.Web/ClientApp/src/App.tsx
  SP23.P03.Web/ClientApp/src/components/AuthProvider.tsx
  SP23.P03.Web/ClientApp/src/components/Nav/Navbar.tsx
  SP23.P03.Web/ClientApp/src/components/SignupModal.tsx
  SP23.P03.Web/ClientApp/src/types/authentication.tsx
  SP23.P03.Web/Controllers/UsersController.cs
Labels: feature, frontend, backend

#60 Trips Scheduling Page
  SP23.P03.Web/ClientApp/src/App.tsx
  SP23.P03.Web/ClientApp/src/components/Nav/Navbar.tsx
  SP23.P03.Web/ClientApp/src/components/RoutePlanner/RoutePlanner.css
  SP23.P03.Web/ClientApp/src/components/RoutePlanner/RoutePlanner.tsx
  SP23.P03.Web/ClientApp/src/components/SignupModal.tsx
  SP23.P03.Web/ClientApp/src/components/StationSelection.tsx
  SP23.P03.Web/ClientApp/src/components/TrainSelection.tsx
  SP23.P03.Web/ClientApp/src/constants/routeconfig.tsx
  SP23.P03.Web/ClientApp/src/helpers/time.tsx
  SP23.P03.Web/ClientApp/src/helpers/trainRoutes.tsx
  SP23.P03.Web/ClientApp/src/helpers/user.tsx
  SP23.P03.Web/ClientApp/src/hooks/api/StationDataService.tsx
  SP23.P03.Web/ClientApp/src/hooks/api/TrainDataService.tsx
  SP23.P03.Web/ClientApp/src/hooks/api/useFindTrain.tsx
  SP23.P03.Web/ClientApp/src/hooks/api/useTrainRoutes.tsx
  SP23.P03.Web/ClientApp/src/hooks/api/useTrips.tsx
  SP23.P03.Web/ClientApp/src/pages/Account/AccountManage.css
  SP23.P03.Web/ClientApp/src/pages/Account/AccountManage.tsx
  SP23.P03.Web/ClientApp/src/pages/Home/HomePage.tsx
  SP23.P03.Web/ClientApp/src/pages/TrainStations/StationListingPage.css
  SP23.P03.Web/ClientApp/src/pages/TrainStations/StationListingPage.tsx
  SP23.P03.Web/ClientApp/src/pages/Trains/TrainListingPage.css
  SP23.P03.Web/ClientApp/src/pages/Trains/TrainListingPage.tsx
  SP23.P03.Web/ClientApp/src/pages/Trips/Trips.css
  SP23.P03.Web/ClientApp/src/pages/Trips/TripsSchedulingPage.tsx
  SP23.P03.Web/ClientApp/src/types/types.tsx
  SP23.P03.Web/Controllers/TrainRoutesController.cs
  SP23.P03.Web/Controllers/TripsController.cs
  SP23.P03.Web/Data/SeedHelper.cs
  SP23.P03.Web/Features/TrainRoutes/TrainRoute.cs
  SP23.P03.Web/Features/TrainRoutes/TrainRouteDto.cs
  SP23.P03.Web/Features/Trips/Trip.cs
Labels: feature, frontend, backend

#63 Feat/train changes
  SP23.P03.Web/Data/SeedHelper.cs
  SP23.P03.Web/Migrations/20230424014211_WipeEverything.Designer.cs
  SP23.P03.Web/Migrations/20230424014211_WipeEverything.cs
Labels: feature, backend

#64 Fix/last minute fixes
  SP23.P03.Web/ClientApp/src/hooks/api/StationDataService.tsx
  SP23.P03.Web/ClientApp/src/hooks/api/TrainDataService.tsx
  SP23.P03.Web/ClientApp/src/pages/TrainStations/StationListingPage.css
  SP23.P03.Web/ClientApp/src/pages/TrainStations/StationListingPage.tsx
  SP23.P03.Web/ClientApp/src/pages/Trains/TrainListingPage.css
  SP23.P03.Web/ClientApp/src/pages/Trains/TrainListingPage.tsx
  SP23.P03.Web/ClientApp/src/pages/Trips/TripsSchedulingPage.tsx
Labels: fix, frontend
